#version 330 compatibility

#define BASIC_LIGHT vec3(END_FOG_COLOR_R * END_ENVIROMENT_BRIGHTNESS, END_FOG_COLOR_G * END_ENVIROMENT_BRIGHTNESS, END_FOG_COLOR_B * END_ENVIROMENT_BRIGHTNESS)

#include "/programs/deferred/Deferred12.frag"
